export const USER_UDPATE = "USER_UDPATE";
export const USER_UDPATE_SUCCESS = "USER_UDPATE_SUCCESS";
export const USER_UDPATE_FAILED = "USER_UDPATE_FAILED";
export const USER_UDPATE_RESET = "USER_UDPATE_RESET";

export const USER_FETCH = "USER_FETCH";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";
export const USER_FETCH_RESET = "USER_FETCH_RESET";
